insert into public.steam_keys (
  platform,
  title,
  region,
  price_label,
  price_value,
  tags,
  aliases,
  cover,
  editions,
  active,
  sort_order
) values
(
  'rockstar',
  'Grand Theft Auto V',
  'Rockstar',
  'по запросу',
  0,
  array['GTA', 'Rockstar'],
  array['gta', 'gta v', 'gta 5', 'гта', 'гта 5', 'rockstar', 'рокстар'],
  '',
  '[{"name":"Standard Edition","region":"Rockstar","priceLabel":"по запросу","priceValue":0,"note":"Ключ Rockstar Launcher"}]'::jsonb,
  true,
  10
),
(
  'rockstar',
  'Red Dead Redemption 2',
  'Rockstar',
  'по запросу',
  0,
  array['RDR', 'Rockstar'],
  array['rdr', 'rdr2', 'red dead', 'ред дед', 'рдр', 'рдр2', 'rockstar', 'рокстар'],
  '',
  '[{"name":"Standard Edition","region":"Rockstar","priceLabel":"по запросу","priceValue":0,"note":"Ключ Rockstar Launcher"}]'::jsonb,
  true,
  20
),
(
  'xbox-keys',
  'Xbox Game Pass Ultimate',
  'TR',
  'по запросу',
  0,
  array['Xbox', 'Game Pass', 'Подписка'],
  array['xbox', 'game pass', 'ultimate', 'иксбокс', 'икс бокс', 'гейм пасс'],
  '',
  '[{"name":"1 месяц","region":"TR","priceLabel":"по запросу","priceValue":0,"note":"Ключ или оформление Xbox Game Pass Ultimate"},{"name":"3 месяца","region":"TR","priceLabel":"по запросу","priceValue":0,"note":"Ключ или оформление Xbox Game Pass Ultimate"}]'::jsonb,
  true,
  10
),
(
  'xbox-keys',
  'Xbox ключ игры',
  'Global',
  'по запросу',
  0,
  array['Xbox', 'Игры'],
  array['xbox key', 'xbox game', 'ключ xbox', 'иксбокс', 'икс бокс'],
  '',
  '[{"name":"Standard Edition","region":"Global","priceLabel":"по запросу","priceValue":0,"note":"Шаблон для Xbox-игры. Переименуй под нужный товар."}]'::jsonb,
  true,
  20
),
(
  'psn-keys',
  'PlayStation Store Card',
  'TR',
  'по запросу',
  0,
  array['PlayStation', 'PSN', 'Карты'],
  array['psn', 'playstation', 'ps5', 'ps store', 'псн', 'плейстейшен'],
  '',
  '[{"name":"PSN Gift Card","region":"TR","priceLabel":"по запросу","priceValue":0,"note":"Код пополнения кошелька PlayStation Network"}]'::jsonb,
  true,
  10
),
(
  'psn-keys',
  'PS5 ключ игры',
  'TR',
  'по запросу',
  0,
  array['PlayStation', 'PS5', 'Игры'],
  array['ps5 key', 'psn game', 'ключ ps5', 'пс5', 'плейстейшен'],
  '',
  '[{"name":"Standard Edition","region":"TR","priceLabel":"по запросу","priceValue":0,"note":"Шаблон для PSN/PS5-игры. Переименуй под нужный товар."}]'::jsonb,
  true,
  20
)
on conflict (platform, title, region) do update set
  price_label = excluded.price_label,
  price_value = excluded.price_value,
  tags = excluded.tags,
  aliases = excluded.aliases,
  cover = excluded.cover,
  editions = excluded.editions,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();
